<?
$aMenuLinks = Array(
	Array(
		"Аллерголог", 
		"/konsultatsiya-allergologa-immunologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Гастроэнтеролог", 
		"/konsultatsiya-gastroenterologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Гинеколог", 
		"/pervichnyy-priem-ginekologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Дерматолог", 
		"/konsultatsiya-dermatologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Диетолог", 
		"/konsultatsiya-dietologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Кардиолог", 
		"/konsultatsiya-kardiologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Колопроктолог", 
		"/konsultatsiya-proktologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Маммолог", 
		"/konsultatsiya-mammologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Невролог", 
		"/konsultatsiya-nevrologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Ортопед", 
		"/konsultatsiya-ortopeda/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Отоларинголог", 
		"/konsultatsiya-otolaringologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Офтальмолог", 
		"/konsultatsiya-oftalmologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Подолог", 
		"/konsultatsiya-podologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Пульмонолог", 
		"/konsultatsiya-pulmonologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Сексолог", 
		"", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Трихолог", 
		"/konsultatsiya-trikhologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Флеболог", 
		"/konsultatsiya-flebologa/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"Хирург", 
		"/konsultatsiya-hirurga/", 
		Array(), 
		Array("tab"=>"Взрослым"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ АЛЛЕРГОЛОГ", 
		"/detskij_allergolog-immunolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ГАСТРОЭНТЕРОЛОГ", 
		"/detskij_gastroenterolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ГЕМАТОЛОГ", 
		"/detskij_gematolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ГИНЕКОЛОГ", 
		"/detskij_ginekolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ДЕРМАТОЛОГ", 
		"/detskij_dermatolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ КАРДИОЛОГ", 
		"/detskij_kardiolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПРОКТОЛОГ", 
		"/detskiy_koloproktolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ЛОГОПЕД", 
		"/detskij_logoped/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ НЕВРОЛОГ", 
		"/detskij_nevrolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ НЕФРОЛОГ", 
		"/detskij_nefrolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ОРТОДОНТ", 
		"/ortodont/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ОТОЛАРИНГОЛОГ", 
		"/detskij_otolaringolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ОФТАЛЬМОЛОГ", 
		"/detskij_oftalmolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ПЕДИАТР", 
		"/pediatr/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПСИХИАТР", 
		"/detskij_psiholog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПСИХОЛОГ", 
		"/detskiy-psikholog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПСИХОТЕРАПЕВТ", 
		"/detskiy-psikhoterapevt/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ РЕВМАТОЛОГ", 
		"/detskij_revmatolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ СТОМАТОЛОГ", 
		"/detskij_stomatolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ УРОЛОГ", 
		"/detskij_urolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ФТИЗИАТР", 
		"/detskiy-ftiziatr/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ХИРУРГ", 
		"/detskij_hirurg/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ЭНДОКРИНОЛОГ", 
		"/detskij_endokrinolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ВЫЗОВ ПЕДИАТРА НА ДОМ", 
		"/vyzov_pediatra_na_dom/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	)
);
?>