<?
$PERM["video"]["*"]="R";
$PERM["/"]["6"]="R";
$PERM["/"]["11"]="W";
$PERM["/"]["*"]="R";
$PERM["index.php"]["*"]="R";
$PERM["desktop_app"]["*"]="D";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["mis"]["1"]="W";
$PERM["mis"]["10"]="W";
$PERM["mis"]["*"]="D";
?>