<?php
$aMenuLinks = array(
    array(
        "Основной",
        "?color=main",
        array(),
        array(),
        ""
    ),
    array(
        "Чёрный",
        "?color=black",
        array(),
        array(),
        ""
    ),
    array(
        "Белый",
        "?color=white",
        array(),
        array(),
        ""
    ),
    array(
        "Зелёный",
        "?color=green",
        array(),
        array(),
        ""
    ),
);