<?
$aMenuLinks = Array(
	Array(
		"Аллергология и Иммунология", 
		"/services/?departmentId=KDTnc4c1&directionId=148207", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Анализы", 
		"/services/?departmentId=KDTnc4c1&directionId=148208", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Вакцинация", 
		"/services/?departmentId=KDTnc4c1&directionId=148209", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Восстановительное лечение", 
		"/services/?departmentId=KDTnc4c1&directionId=148210", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Гастроэнтерология", 
		"/services/?departmentId=KDTnc4c1&directionId=148211", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Гематология", 
		"/services/?departmentId=KDTnc4c1&directionId=148206", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Гинекология и акушерство", 
		"/services/?departmentId=KDTnc4c1&directionId=148212", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Дерматовенерология", 
		"/services/?departmentId=KDTnc4c1&directionId=148213", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Детская клиника", 
		"/services/?departmentId=0DKKEYjv&directionId=148214", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Диетология", 
		"/services/?departmentId=KDTnc4c1&directionId=175447", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Кардиология", 
		"/services/?departmentId=KDTnc4c1&directionId=148225", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Косметология", 
		"https://plastica.onclinic.ru/kosmetologija/", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"ЛОР", 
		"/services/?departmentId=KDTnc4c1&directionId=148227", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Маммология", 
		"/services/?departmentId=KDTnc4c1&directionId=148224", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Мануальная терапия", 
		"/services/?departmentId=KDTnc4c1&directionId=168301", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"МРТ", 
		"/services/?departmentId=KDTnc4c1&directionId=148217", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Неврология", 
		"/services/?departmentId=KDTnc4c1&directionId=148230", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Нейрохирургия", 
		"/services/?departmentId=KDTnc4c1&directionId=168299", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Нефрология", 
		"/services/?departmentId=KDTnc4c1&directionId=168302", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Озонотерапия", 
		"/services/?departmentId=KDTnc4c1&directionId=148237", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Онкология", 
		"/services/?departmentId=KDTnc4c1&directionId=97", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Ортопедия", 
		"/services/?departmentId=KDTnc4c1&directionId=148226", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Офтальмология", 
		"/services/?departmentId=KDTnc4c1&directionId=148228", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Пластическая хирургия", 
		"https://plastica.onclinic.ru/plasticheskaya_hirurgiya/", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Подология", 
		"/services/?departmentId=KDTnc4c1&directionId=148218", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Проктология", 
		"/services/?departmentId=KDTnc4c1&directionId=148216", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Профпатология", 
		"/services/?departmentId=KDTnc4c1&directionId=220020", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Психотерапия", 
		"/services/?departmentId=KDTnc4c1&directionId=148229", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Пульмонология", 
		"/services/?departmentId=KDTnc4c1&directionId=148219", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Ревматология", 
		"/services/?departmentId=KDTnc4c1&directionId=148238", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Рентгенология", 
		"/services/?departmentId=KDTnc4c1&directionId=168303", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Сексология", 
		"/services/?departmentId=KDTnc4c1&directionId=148231", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Стоматология", 
		"/services/?departmentId=KDTnc4c1&directionId=148222", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Терапия", 
		"/services/?departmentId=KDTnc4c1&directionId=148236", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Травматология", 
		"/services/?departmentId=KDTnc4c1&directionId=148239", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Трихология", 
		"/services/?departmentId=KDTnc4c1&directionId=148232", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Ультразвуковая диагностика", 
		"/services/?departmentId=KDTnc4c1&directionId=168304", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Урология", 
		"/services/?departmentId=KDTnc4c1&directionId=148240", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Физиотерапия", 
		"/services/?departmentId=KDTnc4c1&directionId=148220", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Флебология", 
		"/services/?departmentId=KDTnc4c1&directionId=148221", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Функциональная диагностика", 
		"/services/?departmentId=KDTnc4c1&directionId=148215", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Хирургия", 
		"/services/?departmentId=KDTnc4c1&directionId=148233", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Эндокринология", 
		"/services/?departmentId=KDTnc4c1&directionId=148234", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Эндоскопия", 
		"/services/?departmentId=KDTnc4c1&directionId=168306", 
		Array(), 
		Array("tab"=>"Направления"), 
		"" 
	),
	Array(
		"Аллерголог", 
		"/konsultatsiya-allergologa-immunologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Гастроэнтеролог", 
		"/konsultatsiya-gastroenterologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Гинеколог", 
		"/konsultatsiya-ginekologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Дерматолог", 
		"/konsultatsiya-dermatologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Диетолог", 
		"/konsultatsiya-dietologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Кардиолог", 
		"/konsultatsiya-kardiologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"ЛОР", 
		"/konsultatsiya-otolaringologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Маммолог", 
		"/konsultatsiya-mammologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Невролог", 
		"/konsultatsiya-nevrologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Нейрохирург", 
		"/konsultatsiya-neyrohirurga/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Ортопед", 
		"/konsultatsiya-ortopeda/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Офтальмолог", 
		"/konsultatsiya-oftalmologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Подолог", 
		"/konsultatsiya-podologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Проктолог", 
		"/konsultatsiya-proktologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"ПСИХОТЕРАПЕВТ", 
		"/konsultatsiya-psikhoterapevta/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Пульмонолог", 
		"/konsultatsiya-pulmonologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Ревматолог", 
		"/konsultatsiya-revmatologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Сексолог", 
		"/konsultatsiya-seksologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Стоматолог", 
		"/konsultatsiya-stomatologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Травматолог", 
		"/konsultatsiya-travmatologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Трихолог", 
		"/konsultatsiya-trikhologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Уролог", 
		"/konsultatsiya-urologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Флеболог", 
		"/konsultatsiya-flebologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Хирург", 
		"/konsultatsiya-hirurga/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"Эндокринолог", 
		"/konsultatsiya-endokrinologa/", 
		Array(), 
		Array("tab"=>"Консультации врачей"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ АЛЛЕРГОЛОГ", 
		"/detskij-allergolog-immunolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ГАСТРОЭНТЕРОЛОГ", 
		"/detskij-gastroenterolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ГЕМАТОЛОГ", 
		"/detskij-gematolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ГИНЕКОЛОГ", 
		"/detskij-ginekolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ДЕРМАТОЛОГ", 
		"/detskij-dermatolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ КАРДИОЛОГ", 
		"/detskij-kardiolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПРОКТОЛОГ", 
		"/detskiy-koloproktolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ЛОГОПЕД", 
		"/detskij-logoped/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ НЕВРОЛОГ", 
		"/detskij-nevrolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ НЕФРОЛОГ", 
		"/detskij-nefrolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ОРТОДОНТ", 
		"/ortodont/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ОТОЛАРИНГОЛОГ", 
		"/detskij-otolaringolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ОФТАЛЬМОЛОГ", 
		"/detskij-oftalmolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ПЕДИАТР", 
		"/pediatr/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПСИХИАТР", 
		"/detskij-psiholog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПСИХОЛОГ", 
		"/detskiy-psikholog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ПСИХОТЕРАПЕВТ", 
		"/detskiy-psikhoterapevt/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ РЕВМАТОЛОГ", 
		"/detskij-revmatolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ СТОМАТОЛОГ", 
		"/detskij-stomatolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ УРОЛОГ", 
		"/detskij-urolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ФТИЗИАТР", 
		"/detskiy-ftiziatr/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ХИРУРГ", 
		"/detskij-hirurg/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ДЕТСКИЙ ЭНДОКРИНОЛОГ", 
		"/detskij-endokrinolog/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	),
	Array(
		"ВЫЗОВ ПЕДИАТРА НА ДОМ", 
		"/vyzov-pediatra-na-dom/", 
		Array(), 
		Array("tab"=>"Детям"), 
		"" 
	)
);
?>