<?
$aMenuLinks = Array(
	Array(
		"Аллергологи-иммунологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148207", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Гастроэнтерологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148211", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Гематологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148206", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Гинекологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148212", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Дерматовенерологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148213", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Детские врачи", 
		"/doctors/?departmentId=0DKKEYjv", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Кардиологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148225", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Колопроктологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148216", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Маммологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148224", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Мануальные терапевты", 
		"/doctors/?departmentId=&directionId=168301", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Неврологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148230", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Нейрохирурги", 
		"/doctors/?departmentId=KDTnc4c1&directionId=168299", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Оториноларингологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148227", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Офтальмологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148228", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Пластические хирурги", 
		"https://plastica.onclinic.ru/doctors/", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Психотерапевты", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148229", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Пульмонологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148219", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Ревматологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148238", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Рентгенологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=168303", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Сексологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148231", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Стоматологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148222", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Терапевты", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148236", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Травматологи-ортопеды", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148226", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Трихологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148232", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"УЗ-диагносты", 
		"/doctors/?departmentId=KDTnc4c1&directionId=168304", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Урологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148240", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Физиотерапевты", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148220", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Флебологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148221", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Хирурги", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148233", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Эндокринологи", 
		"/doctors/?departmentId=KDTnc4c1&directionId=148234", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	),
	Array(
		"Эндоскописты", 
		"/doctors/?departmentId=KDTnc4c1&directionId=168306", 
		Array(), 
		Array("tab"=>"Специализации"), 
		"" 
	)
);
?>